<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "product_file".
 *
 * @property integer $product_id
 * @property integer $file_id
 *
 * @property \app\models\File $file
 * @property \app\models\Product $product
 */
abstract class ProductFile extends \app\components\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_file';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['product_id', 'file_id'], 'required'],
            [['product_id', 'file_id'], 'default', 'value' => null],
            [['product_id', 'file_id'], 'integer'],
            [['product_id', 'file_id'], 'unique', 'targetAttribute' => ['product_id', 'file_id']],
            [['file_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\File::class, 'targetAttribute' => ['file_id' => 'id']],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Product::class, 'targetAttribute' => ['product_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'product_id' => 'Product ID',
            'file_id' => 'File ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFile()
    {
        return $this->hasOne(\app\models\File::class, ['id' => 'file_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(\app\models\Product::class, ['id' => 'product_id']);
    }

}
