<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "project".
 *
 * @property integer $id
 * @property string $title
 * @property string $text
 * @property string $place
 * @property string $image
 */
abstract class Project extends \app\components\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'project';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['title', 'text', 'place'], 'required'],
            [['title', 'text', 'place', 'image'], 'string']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'title' => 'Title',
            'text' => 'Text',
            'place' => 'Place',
            'image' => 'Image',
        ]);
    }

}
