<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "user".
 *
 * @property integer $id
 * @property string $email
 * @property string $password
 * @property boolean $is_activated
 * @property string $activation_link
 *
 * @property \app\models\Token $token
 */
abstract class User extends \app\components\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['email', 'password'], 'required'],
            [['email', 'password', 'activation_link'], 'string'],
            [['is_activated'], 'boolean'],
            [['email'], 'unique']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'email' => 'Email',
            'password' => 'Password',
            'is_activated' => 'Is Activated',
            'activation_link' => 'Activation Link',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getToken()
    {
        return $this->hasOne(\app\models\Token::class, ['user_id' => 'id']);
    }

}
